networks:
  net:
    name: jumbo

services:
  jumbo-api:
    build: .
    container_name: jumbo-api
    ports:
      - '3000:3000'
      - '3001:3001'
    networks:
      - net
    environment:
      - DISABLE_DOTENV=true
    env_file:
      - .env

  mongo:
    image: mongo
    container_name: jumbo-mongo
    volumes:
      - mongo:/data/db
    networks:
      - net
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass123

  mongo-express:
    image: mongo-express
    container_name: jumbo-mongo-express
    networks:
      - net
    ports:
      - 8001:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass123
      ME_CONFIG_MONGODB_URL: mongodb://root:pass123@mongo:27017/
    depends_on:
      - mongo

volumes:
  mongo:
    name: jumbo-mongo
